extends DynamicContextControl


const FALLBACK_THUMBNAIL = preload("uid://bpkx70rl1xv4t")


@onready var text_edit_description: TextEdit = %TextEditDescription
@onready var line_edit_authors: LineEdit = %LineEditAuthors
# Thumbnail
@onready var thumbnail_texture_rect: TextureRect = %ThumbnailTextureRect
@onready var autogenerated_label: Label = %AutogeneratedLabel
@onready var create_thumbnail_button: Button = %CreateThumbnailButton


var _workspace_context: WorkspaceContext = null
var _loading: bool = false

var _thumbnail_history: Array[Texture2D] = []

func _ready() -> void:
	text_edit_description.text_changed.connect(_on_text_edit_description_text_changed)
	line_edit_authors.text_changed.connect(_on_line_edit_authors_text_changed)
	text_edit_description.focus_exited.connect(_on_text_edit_description_focus_exited)
	line_edit_authors.focus_exited.connect(_on_line_edit_authors_focus_exited)
	create_thumbnail_button.pressed.connect(_on_create_thumbnail_button_pressed)
	MolecularEditorContext.workspace_saved.connect(_on_workspace_saved)


func should_show(in_workspace_context: WorkspaceContext)-> bool:
	if _workspace_context == null:
		_workspace_context = in_workspace_context
		_workspace_context.history_snapshot_applied.connect(_on_workspace_context_history_snapshot_applied)
	load_settings()
	return true


func _on_text_edit_description_text_changed() -> void:
	const CREATE_SNAPSHOT = false # Dont create snapshot because have not finished editing
	_update_workspace_description(CREATE_SNAPSHOT)


func _on_line_edit_authors_text_changed(_in_new_text: String) -> void:
	const CREATE_SNAPSHOT = false # Dont create snapshot because have not finished editing
	_update_workspace_authors(CREATE_SNAPSHOT)


func _on_text_edit_description_focus_exited() -> void:
	const CREATE_SNAPSHOT = true # Creating snapshot because finished editing
	_update_workspace_description(CREATE_SNAPSHOT)


func _on_line_edit_authors_focus_exited() -> void:
	const CREATE_SNAPSHOT = true # Creating snapshot because finished editing
	_update_workspace_authors(CREATE_SNAPSHOT)


func _update_workspace_description(in_create_snapshot: bool) -> void:
	if !_loading and _workspace_context != null:
		if _workspace_context.workspace.description != text_edit_description.text:
			_workspace_context.workspace.description = text_edit_description.text
			if in_create_snapshot:
				_workspace_context.snapshot_moment("Set Description")


func _update_workspace_authors(in_create_snapshot: bool) -> void:
	if !_loading and _workspace_context != null:
		if _workspace_context.workspace.authors != line_edit_authors.text:
			_workspace_context.workspace.authors = line_edit_authors.text
			if in_create_snapshot:
				_workspace_context.snapshot_moment("Set Authors")


func _on_workspace_context_history_snapshot_applied() -> void:
	load_settings()


func load_settings() -> void:
	if _workspace_context == null:
		return
	_loading = true
	text_edit_description.text = _workspace_context.workspace.description
	line_edit_authors.text = _workspace_context.workspace.authors
	_thumbnail_history = []
	var current: Texture2D = _workspace_context.workspace.get_thumbnail()
	if current != null:
		_thumbnail_history.push_back(current)
	_set_thumbnail(current, _workspace_context.workspace.is_last_thumbnail_user_generated)
	_loading = false


func _set_thumbnail(in_thumbnail: Texture2D, is_user_generated: bool) -> void:
	if in_thumbnail == null:
		thumbnail_texture_rect.texture = FALLBACK_THUMBNAIL
	else:
		thumbnail_texture_rect.texture = in_thumbnail
	var is_autogenerated: bool = in_thumbnail != null and not is_user_generated
	autogenerated_label.visible = is_autogenerated


func _on_create_thumbnail_button_pressed() -> void:
	var img: Image = WorkspaceUtils.generate_thumbnail(_workspace_context.workspace)
	_workspace_context.workspace.set_thumbnail(img, true)
	var current: Texture2D = _workspace_context.workspace.get_thumbnail()
	if current != null:
		_thumbnail_history.push_back(current)
	_set_thumbnail(current, true)
	_workspace_context.snapshot_moment("Set Project Thumbnail")


func _on_workspace_saved(in_workspace: Workspace) -> void:
	if in_workspace != _workspace_context.workspace:
		return
	# Check if thumbnail has changed when saving
	_set_thumbnail(in_workspace.get_thumbnail(), in_workspace.is_last_thumbnail_user_generated)
