class_name ShareProjectDialog extends NanoAcceptDialog

var _new_project_check_box: CheckBox
var _new_project_line_edit: LineEdit
var _existing_project_check_box: CheckBox
var _existing_project_option_button: OptionButton
var _description_text_edit: TextEdit
var _authors_line_edit: LineEdit
var _thumbnail_texture_rect: TextureRect
var _autogenerated_label: Label
var _revert_thumbnail_button: Button
var _create_thumbnail_button: Button
var _workspace_provenance_editor: VBoxContainer


var _workspace: Workspace

func _init() -> void:
	hide()


func _notification(what: int) -> void:
	if what == NOTIFICATION_SCENE_INSTANTIATED:
		_new_project_check_box = %NewProjectCheckBox as CheckBox
		_new_project_line_edit = %NewProjectLineEdit as LineEdit
		_existing_project_check_box = %ExistingProjectCheckBox as CheckBox
		_existing_project_option_button = %ExistingProjectOptionButton as OptionButton
		_description_text_edit = %DescriptionTextEdit as TextEdit
		_authors_line_edit = %AuthorsLineEdit as LineEdit
		_thumbnail_texture_rect = %ThumbnailTextureRect as TextureRect
		_autogenerated_label = %AutogeneratedLabel as Label
		_revert_thumbnail_button = %RevertThumbnailButton as Button
		_create_thumbnail_button = %CreateThumbnailButton as Button
		_workspace_provenance_editor = %WorkspaceProvenanceEditor as VBoxContainer
		
		about_to_popup.connect(_on_about_to_popup)
		
		_new_project_check_box.button_group.pressed.connect(_new_or_existing_project_check_box_pressed.unbind(1))
		_revert_thumbnail_button.pressed.connect(_on_revert_thumbnail_button_pressed)
		_create_thumbnail_button.pressed.connect(_on_create_thumbnail_button_pressed)


# OVERRIDE
func _on_confirmed() -> void:
	# TODO: Upload the file and run rest apis
	super._on_confirmed()


# OVERRIDE
func _on_canceled() -> void:
	super._on_canceled()


func _on_about_to_popup() -> void:
	var workspace: Workspace = MolecularEditorContext.get_current_workspace()
	assert(workspace != null, "Share dialog cannot be open from the Welcome page")
	assert(not workspace.resource_path.is_empty(), "Workspace should be saved at least once before sharing")
	_workspace = workspace
	# TODO: Read if project has already been uploaded
	# select new or existing checkbox
	# Fill the Combo button with existing projects for the user
	var user_has_projects: bool = false #(FIXME)
	_new_project_line_edit.text = workspace.get_user_friendly_name()
	if user_has_projects:
		_existing_project_check_box.disabled = false
		#TODO: if file is linked to an existing project, select checkbox and option button
	else:
		_new_project_check_box.button_pressed = true
		_existing_project_check_box.disabled = true
		_existing_project_option_button.clear()
		_existing_project_option_button.disabled = true
	_description_text_edit.text = workspace.description
	_authors_line_edit.text = workspace.authors
	_thumbnail_texture_rect.texture = workspace.get_thumbnail()
	_autogenerated_label.visible = not workspace.is_last_thumbnail_user_generated
	_revert_thumbnail_button.hide()
	_workspace_provenance_editor.setup(workspace)


func _new_or_existing_project_check_box_pressed() -> void:
	_new_project_line_edit.editable = _new_project_check_box.button_pressed
	_existing_project_option_button.disabled = not _existing_project_check_box.button_pressed


func _on_revert_thumbnail_button_pressed() -> void:
	_thumbnail_texture_rect.texture = _workspace.get_thumbnail()
	if _thumbnail_texture_rect.texture == null:
		_thumbnail_texture_rect.texture = preload("uid://bpkx70rl1xv4t")
	_autogenerated_label.visible = not _workspace.is_last_thumbnail_user_generated
	_revert_thumbnail_button.hide()
	_create_thumbnail_button.disabled = false


func _on_create_thumbnail_button_pressed() -> void:
	var img: Image = WorkspaceUtils.generate_thumbnail(_workspace)
	var new_thumbnail: Texture2D = ImageTexture.create_from_image(img)
	_thumbnail_texture_rect.texture = new_thumbnail
	_autogenerated_label.hide()
	_revert_thumbnail_button.show()
	_create_thumbnail_button.disabled = true

