class_name ShareProjectDialog extends NanoAcceptDialog


const ExistingProjectOptionButton: Script = preload("uid://xp3byufpryt0")


var _existing_project_option_button: ExistingProjectOptionButton
var _edit_project_button: Button
var _new_project_button: Button
var _description_label: Label
var _tags_main_container: VBoxContainer
var _collaborators_main_container: VBoxContainer
var _tag_list_container: HFlowContainer
var _collaborators_list_container: HFlowContainer
var _version_description_text_edit: TextEdit
var _thumbnail_texture_rect: TextureRect
var _autogenerated_label: Label
var _revert_thumbnail_button: Button
var _create_thumbnail_button: Button
var _workspace_provenance_editor: VBoxContainer

var _loading_controls: Array[Control]
var _tags: Array[TagLabel]
var _collaborators: Array[CollaboratorLabel]

var _workspace: Workspace
var _tags_promise: Promise
var _collabs_promise: Promise


var _selected_project_data: Dictionary


func _init() -> void:
	super._init()
	hide()
	get_ok_button().pressed.connect(_on_ok_button_pressed)


func _notification(what: int) -> void:
	if what == NOTIFICATION_SCENE_INSTANTIATED:
		_existing_project_option_button = %ExistingProjectOptionButton as ExistingProjectOptionButton
		_edit_project_button = %EditProjectButton as Button
		_new_project_button = %NewProjectButton as Button
		_description_label = %DescriptionLabel as Label
		_tags_main_container = %TagsMainContainer as VBoxContainer
		_collaborators_main_container = %CollaboratorsMainContainer as VBoxContainer
		_tag_list_container = %TagListContainer as  HFlowContainer
		_collaborators_list_container = %CollaboratorsListContainer as  HFlowContainer
		_version_description_text_edit = %VersionDescriptionTextEdit as TextEdit
		_thumbnail_texture_rect = %ThumbnailTextureRect as TextureRect
		_autogenerated_label = %AutogeneratedLabel as Label
		_revert_thumbnail_button = %RevertThumbnailButton as Button
		_create_thumbnail_button = %CreateThumbnailButton as Button
		_workspace_provenance_editor = %WorkspaceProvenanceEditor as VBoxContainer
		
		_loading_controls = [
			%LoadingDescriptionLabel,
			%LoadingTagLabel,
			%LoadingCollaboratorLabel,
		]
		
		about_to_popup.connect(_on_about_to_popup)
		_existing_project_option_button.project_selected.connect(_on_project_selected)
		_edit_project_button.pressed.connect(_on_edit_project_button_pressed)
		_new_project_button.pressed.connect(_on_new_project_button_pressed)
		_revert_thumbnail_button.pressed.connect(_on_revert_thumbnail_button_pressed)
		_create_thumbnail_button.pressed.connect(_on_create_thumbnail_button_pressed)



func _on_project_selected(project_data_or_empty: Dictionary) -> void:
	_selected_project_data = project_data_or_empty
	_clear_ui()
	if project_data_or_empty.is_empty():
		return
	for control in _loading_controls:
		control.hide()
	_edit_project_button.disabled = false
	_description_label.show()
	_description_label.text = project_data_or_empty.description
	_update_tags(_existing_project_option_button.get_selected_project_tags_async())

	_update_collaborators(_existing_project_option_button.get_selected_project_collaborators_async())
	# TODO


func _update_tags(in_promise: Promise) -> void:
	_tags_main_container.show()
	_tags_promise = in_promise
	await in_promise.wait_for_fulfill()
	if _tags_promise != in_promise:
		# Another request to fetch tags was made before this one ended
		return
	if in_promise.has_error():
		# Failed to fetch tags. What should the system do in this case?
		# In theory rightn ow the "loading" label is still and will remain spinning
		return
	var data: Dictionary = in_promise.get_result().body
	assert(data.has("tags"))
	if data.tags.is_empty():
		_tags_main_container.hide()
		return
	for tag: String in data.tags:
		const SHOULD_SHOW_ERASE_BUTTON = false
		var tag_label := TagLabel.create_tag(tag, SHOULD_SHOW_ERASE_BUTTON)
		_tags.append(tag_label)
		_tag_list_container.add_child(tag_label)
	_tags_promise = null


func _update_collaborators(in_promise: Promise) -> void:
	_collaborators_main_container.show()
	_collabs_promise = in_promise
	await in_promise.wait_for_fulfill()
	if _collabs_promise != in_promise:
		# Another request to fetch collaborators was made before this one ended
		return
	if in_promise.has_error():
		# Failed to fetch collaborators. What should the system do in this case?
		# In theory rightn ow the "loading" label is still and will remain spinning
		return
	var data: Dictionary = in_promise.get_result().body
	assert(data.has("collaborators"))
	if data.collaborators.is_empty():
		_collaborators_main_container.hide()
		return
	for collaborator: Dictionary in data.collaborators:
		const SHOULD_SHOW_ERASE_BUTTON = false
		var collaborator_label := CollaboratorLabel.create_collaborator(
			collaborator.name, collaborator.email, SHOULD_SHOW_ERASE_BUTTON
		)
		_collaborators.append(collaborator_label)
		_collaborators_list_container.add_child(collaborator_label)
	_collabs_promise = null


func _on_edit_project_button_pressed() -> void:
	DisplayServer.dialog_show("TODO", "This feature is under development", ["OK"], Callable())


func _on_new_project_button_pressed() -> void:
	hide()
	var create_dlg: CreateProjectDialog = preload("uid://b1kit4646fm5f").instantiate()
	get_parent().add_child(create_dlg)
	create_dlg.popup_centered()
	await create_dlg.closed
	create_dlg.queue_free()
	popup_centered()


func _clear_ui() -> void:
	_tags_main_container.show()
	_collaborators_main_container.show()
	for control in _loading_controls:
		control.show()
	_edit_project_button.disabled = true
	_description_label.hide()
	for tag in _tags:
		tag.queue_free()
	_tags.clear()
	for collab in _collaborators:
		collab.queue_free()
	_collaborators.clear()
	


# OVERRIDE
func _on_confirmed() -> void:
	# TODO: Upload the file and run rest apis
	super._on_confirmed()


# OVERRIDE
func _on_canceled() -> void:
	super._on_canceled()


func _on_about_to_popup() -> void:
	var workspace: Workspace = MolecularEditorContext.get_current_workspace()
	assert(workspace != null, "Share dialog cannot be open from the Welcome page")
	assert(not workspace.resource_path.is_empty(), "Workspace should be saved at least once before sharing")
	_workspace = workspace
	_clear_ui()
	_thumbnail_texture_rect.texture = workspace.get_thumbnail()
	_autogenerated_label.visible = not workspace.is_last_thumbnail_user_generated
	_revert_thumbnail_button.hide()
	_workspace_provenance_editor.setup(workspace)


func _format_project_name(text: String) -> String:
	return text.to_lower().replace(" ", "-").replace("_", "-")


func _on_revert_thumbnail_button_pressed() -> void:
	_thumbnail_texture_rect.texture = _workspace.get_thumbnail()
	if _thumbnail_texture_rect.texture == null:
		_thumbnail_texture_rect.texture = preload("uid://bpkx70rl1xv4t")
	_autogenerated_label.visible = not _workspace.is_last_thumbnail_user_generated
	_revert_thumbnail_button.hide()
	_create_thumbnail_button.disabled = false


func _on_create_thumbnail_button_pressed() -> void:
	var img: Image = WorkspaceUtils.generate_thumbnail(_workspace)
	var new_thumbnail: Texture2D = ImageTexture.create_from_image(img)
	_thumbnail_texture_rect.texture = new_thumbnail
	_autogenerated_label.hide()
	_revert_thumbnail_button.show()
	_create_thumbnail_button.disabled = true


func _on_ok_button_pressed() -> void:
	var ok_button: Button = get_ok_button()
	# We need to cast self to Variant in order to call get_cancel_button()
	# Because GdScript is confused with the ingeritance chain
	var dialog: Variant = self
	var cancel_button: Button = dialog.get_cancel_button()
	ok_button.disabled = true
	cancel_button.disabled = true
	ok_button_text = tr(&"Uploading")
	gui_disable_input = true
	var file_path: String = MolecularEditorContext.get_current_workspace().resource_path
	MolecularEditorContext.save_workspace(
		MolecularEditorContext.get_current_workspace(),
		file_path
	)
	var file := FileAccess.open(file_path, FileAccess.READ)
	var promise: Promise = MolecularEditorContext.msep_online_service.post_namespace_project_version(
		_selected_project_data.namespace,
		_selected_project_data.name,
		_version_description_text_edit.text,
		file
	)
	await promise.wait_for_fulfill()
	ok_button.disabled = false
	cancel_button.disabled = false
	ok_button_text = tr(&"Save changes and Share")
	gui_disable_input = false
	if promise.has_error():
		MolecularEditorContext.get_current_workspace_context().show_warning_dialog(
			promise.get_error(), tr(&"OK")
		)
	else:
		hide()
